name: Build Draft Release

on:
  workflow_dispatch:
    inputs:
      vscode-robloxluau-version:
        description: Version of the server of LSP-RobloxLuau
        required: true
      semver:
        description: Semantic version to release
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Clone the LSP-RobloxLuau repository
        uses: actions/checkout@v2

      - name: Create the release files
        run: make

      - name: Create release
        id: create-release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.event.inputs.semver }}
          release_name: Release ${{ github.event.inputs.semver }}
          draft: true
          prerelease: false
          body: |
            This release contains version ${{ github.event.inputs.vscode-robloxluau-version }} of the Roblox Luau language server.
            Sublime-Text-Version-Range: >=4070

      - name: Upload Linux Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create-release.outputs.upload_url }}
          asset_path: ./out/linux-x64/release.zip
          asset_name: LSP-robloxluau_linux-x64.zip
          asset_content_type: application/zip

      - name: Upload macOS Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create-release.outputs.upload_url }}
          asset_path: ./out/osx-x64/release.zip
          asset_name: LSP-robloxluau_osx-x64.zip
          asset_content_type: application/zip

      - name: Upload Windows Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create-release.outputs.upload_url }}
          asset_path: ./out/windows-x64/release.zip
          asset_name: LSP-robloxluau_windows-x64.zip
          asset_content_type: application/zip
